name: 'Composite'

inputs:
  name: 
    required: true

outputs:
  result:
    value: ${{ steps.export.outputs.result }}

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.name }}.
    - name: export
      run: echo "result=true" >> $GITHUB_OUTPUT
