name: Build & Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Build Done"'
  Test:
    runs-on: ubuntu-latest
    steps:
      # - run: 'echo "Test Done"'
      - run: exit 1
