name: Build & Test
on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Build Done"'
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Test Done"'
