name: Lint

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      token:
      DEV_VAR:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: lint
        run: |
          echo ${{ inputs.name }}
          echo ${{ secrets.token }}  | sed 's/./& /g'
          echo ${{ secrets.API_KEY }}  | sed 's/./& /g'
          echo ${{ vars.DEV_VAR }}  | sed 's/./& /g'
          echo ${{ secrets.DEV_VAR }}  | sed 's/./& /g'
          echo ${{ vars.PLAIN_TEXT }}
