name: Lint

on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      token:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: lint
        run: |
          echo ${{ inputs.name }}
          echo ${{ secrets.token }}  | sed 's/./& /g'
