name: Tests
on: [push]

jobs:
  test-node:
    name: 'Node.js'
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: actions/checkout@v3
      - name: legacy output
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: legacy output echo 
        run: echo ${{ steps.npm-cache.outputs.dir }}
      
      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      
      - name: new output test
        id: new-test
        run: |
          echo "dir=hello" >> $GITHUB_OUTPUT
      - name: new output test echo 
        run: echo ${{ steps.new-test.outputs.dir }}
      - name: new output
        id: new-cached
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - name: new output echo 
        run: echo ${{ steps.new-cached.outputs }} | jq .
      - name: new output echo 
        run: echo ${{ steps.new-cached.outputs.dir }}
      