name: Output

on: [push, workflow_dispatch]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - id: version1
        run: echo "::set-output name=VERSION1::1.3.2"
      - run: echo ${{ steps.version1.outputs.VERSION1 }}
      - run: echo "VERSION2=2.5.4" >> $GITHUB_ENV
      - run: echo "${{ env.VERSION2 }}"
